# Generated by Django 4.1.13 on 2024-01-22 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
    ]
