# Generated by Django 4.1.13 on 2024-01-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_remove_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_heading",
            field=models.CharField(default="", max_length=200),
        ),
    ]
